name: ROS2 Jazzy CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-in-sim:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build CI Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.sim
          tags: amr_nav:ci
          load: true

      - name: Run Unit Tests
        run: |          
          docker run --rm amr_nav:ci \
            bash -c " \
              source /opt/ros/jazzy/setup.bash && \
              source /ros2_ws/install/setup.bash && \
              pytest tests/unit \
            "

      # - name: Run Integration Tests (Headless)
      #   run: |
      #     docker run --rm --env ROS_DOMAIN_ID=99 amr_nav:ci \
      #       bash -c " \ 
      #         source /opt/ros/jazzy/setup.bash && \
      #         source /ros2_ws/install/setup.bash && \
      #         pytest tests/integration
      #       "

  runtime-image:
    needs: build-in-sim
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to registry(Docker Hub)
      #   uses: docker/login-action@v3        
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to registry(GitHub Container Registry (GHCR))
        uses: docker/login-action@v3        
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push runtime image (ARM64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.runtime
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/jinho-edu/ros2-amr-project:latest
            ghcr.io/jinho-edu/ros2-amr-project:sha-${{ github.sha }}
            
